# The path to the snpEff.jar file.
snpEff: #command and options of snpEff annotation
    jar: "~/Downloads/Tempus/snpEff/snpEff.jar"
    params: ""

# The URL root of the ExAC server
exacServer: "http://exac.hms.harvard.edu"

